backend:
  name: github
  repo: suresh-kumara-gist/verify-github-app-frontend
  branch: main
  base_url: https://suresh-issue-82.dcycleproject.org
  auth_endpoint: /auth/github/repo/695e2601cf43ed317a80e870
